spring:
    application:
        name: devfest2024_back
    datasource:
        url: jdbc:postgresql://localhost:5432/compose-postgres
        username: compose-postgres
        password: compose-postgres
    jpa:
        hibernate:
            ddl-auto: none
    liquibase:
        enabled: true
        change-log: classpath:/db/changelog.yml
cors:
    allowed-origin: "*"
    allowed-method: '*'
    allowed-header: '*'
    allow-credentials: true

